/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/onboarding/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardStaff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/onboarding/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardOwner"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/work-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영 로그 목록 조회 */
        get: operations["getWorkLogList"];
        put?: never;
        /** 운영 로그 작성 */
        post: operations["createWorkLog"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/notices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 공지 목록 조회 */
        get: operations["getNoticeList"];
        put?: never;
        /** 공지 등록 */
        post: operations["createNotice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/expiry-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유통기한 상품 목록 조회 */
        get: operations["getExpiryItemList"];
        put?: never;
        /** 유통기한 상품 등록 */
        post: operations["createExpiryItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/presigned-url": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createUploadUrl"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reissue"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/kakao/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["kakaoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch: operations["updateName"];
        trace?: never;
    };
    "/groups/{groupId}/work-logs/{workLogId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 운영 로그 상세 조회 */
        get: operations["getWorkLog"];
        put?: never;
        post?: never;
        /** 운영 로그 삭제 */
        delete: operations["deleteWorkLog"];
        options?: never;
        head?: never;
        /** 운영 로그 수정 */
        patch: operations["updateWorkLog"];
        trace?: never;
    };
    "/groups/{groupId}/notices/{noticeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 공지 상세 조회 */
        get: operations["getNotice"];
        put?: never;
        post?: never;
        /** 공지 삭제 */
        delete: operations["deleteNotice"];
        options?: never;
        head?: never;
        /** 공지 수정 */
        patch: operations["updateNotice"];
        trace?: never;
    };
    "/groups/{groupId}/expiry-items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 유통기한 상품 상세 조회 */
        get: operations["getExpiryItem"];
        put?: never;
        post?: never;
        /** 유통기한 상품 삭제 */
        delete: operations["deleteExpiryItem"];
        options?: never;
        head?: never;
        /** 유통기한 상품 수정 */
        patch: operations["updateExpiryItem"];
        trace?: never;
    };
    "/groups/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMyGroup"];
        put?: never;
        post?: never;
        delete: operations["deleteMyGroup"];
        options?: never;
        head?: never;
        patch: operations["updateMyGroup"];
        trace?: never;
    };
    "/groups/me/invite-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["reissueInviteCode"];
        trace?: never;
    };
    "/groups/{groupId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/groups/{groupId}/members/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["leave"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        StaffOnboardingRequest: {
            name: string;
            inviteCode: string;
        };
        ApiResponseStaffOnboardingResponse: {
            success?: boolean;
            data?: components["schemas"]["StaffOnboardingResponse"];
            message?: string;
        };
        StaffOnboardingResponse: {
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            /** @enum {string} */
            storeBrand?: "GS25" | "CU" | "SEVEN_ELEVEN" | "EMART24";
        };
        OwnerOnboardingRequest: {
            name: string;
            /** @enum {string} */
            storeBrand: "GS25" | "CU" | "SEVEN_ELEVEN" | "EMART24";
            storeName: string;
        };
        ApiResponseOwnerOnboardingResponse: {
            success?: boolean;
            data?: components["schemas"]["OwnerOnboardingResponse"];
            message?: string;
        };
        OwnerOnboardingResponse: {
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            /** @enum {string} */
            storeBrand?: "GS25" | "CU" | "SEVEN_ELEVEN" | "EMART24";
            inviteCode?: string;
        };
        CreateWorkLogRequest: {
            /**
             * @description 운영 로그 내용
             * @example 냉장고 온도가 일시적으로 높아져 점검 요청했습니다.
             */
            content: string;
        };
        ApiResponseWorkLogResponse: {
            success?: boolean;
            data?: components["schemas"]["WorkLogResponse"];
            message?: string;
        };
        WorkLogResponse: {
            /**
             * Format: int64
             * @description 운영 로그 ID
             * @example 1
             */
            workLogId?: number;
            /**
             * @description 운영 로그 내용
             * @example 냉장고 온도가 일시적으로 높아져 점검 요청했습니다.
             */
            content?: string;
            /**
             * Format: int64
             * @description 작성자 유저 ID
             * @example 1
             */
            authorUserId?: number;
            /**
             * @description 작성자 이름
             * @example 홍길동
             */
            authorName?: string;
            /**
             * Format: date-time
             * @description 작성 시각
             * @example 2026-07-02T10:30:00
             */
            createdAt?: string;
        };
        CreateNoticeRequest: {
            /**
             * @description 공지 제목
             * @example 신상품 입고 안내
             */
            title: string;
            /**
             * @description 공지 내용
             * @example 오늘 야간 근무자는 신상품 진열 상태를 확인해주세요.
             */
            content: string;
            /**
             * @description 공지 태그
             * @example DAILY
             * @enum {string}
             */
            tag: "DAILY" | "WEEKLY";
            /**
             * @description 첨부 이미지 URL
             * @example https://example.com/notices/image.png
             */
            imageUrl?: string;
        };
        ApiResponseNoticeResponse: {
            success?: boolean;
            data?: components["schemas"]["NoticeResponse"];
            message?: string;
        };
        NoticeResponse: {
            /**
             * Format: int64
             * @description 공지 ID
             * @example 1
             */
            noticeId?: number;
            /**
             * @description 공지 제목
             * @example 신상품 입고 안내
             */
            title?: string;
            /**
             * @description 공지 내용
             * @example 오늘 야간 근무자는 신상품 진열 상태를 확인해주세요.
             */
            content?: string;
            /**
             * @description 공지 태그
             * @example DAILY
             * @enum {string}
             */
            tag?: "DAILY" | "WEEKLY";
            /**
             * @description 첨부 이미지 URL
             * @example https://example.com/notices/image.png
             */
            imageUrl?: string;
            /**
             * Format: int64
             * @description 작성자 유저 ID
             * @example 1
             */
            authorUserId?: number;
            /**
             * @description 작성자 이름
             * @example 홍길동
             */
            authorName?: string;
            /**
             * Format: date-time
             * @description 작성 시각
             * @example 2026-07-02T10:30:00
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 표시 시작 시각
             * @example 2026-07-02T00:00:00
             */
            displayStartAt?: string;
            /**
             * Format: date-time
             * @description 표시 종료 시각, exclusive 기준
             * @example 2026-07-03T00:00:00
             */
            displayEndAt?: string;
        };
        CreateExpiryItemRequest: {
            /**
             * @description 상품명
             * @example 삼각김밥 참치마요
             */
            productName: string;
            /**
             * Format: date
             * @description 유통기한
             * @example 2026-07-10
             */
            expireDate: string;
            /**
             * @description 상품 이미지 URL
             * @example https://example.com/expiry-items/image.png
             */
            imageUrl: string;
        };
        ApiResponseExpiryItemResponse: {
            success?: boolean;
            data?: components["schemas"]["ExpiryItemResponse"];
            message?: string;
        };
        ExpiryItemResponse: {
            /**
             * Format: int64
             * @description 유통기한 상품 ID
             * @example 1
             */
            expiryItemId?: number;
            /**
             * @description 상품명
             * @example 삼각김밥 참치마요
             */
            productName?: string;
            /**
             * Format: date
             * @description 유통기한
             * @example 2026-07-10
             */
            expireDate?: string;
            /**
             * @description 상품 이미지 URL
             * @example https://example.com/expiry-items/image.png
             */
            imageUrl?: string;
            /**
             * Format: int64
             * @description 작성자 유저 ID
             * @example 1
             */
            authorUserId?: number;
            /**
             * @description 작성자 이름
             * @example 홍길동
             */
            authorName?: string;
            /**
             * Format: date-time
             * @description 작성 시각
             * @example 2026-07-02T10:30:00
             */
            createdAt?: string;
            /** Format: int64 */
            dday?: number;
        };
        PresignedUploadUrlRequest: {
            fileName: string;
            contentType: string;
            /** @enum {string} */
            domain: "NOTICE" | "EXPIRY_ITEM" | "PROFILE";
        };
        ApiResponsePresignedUploadUrlResponse: {
            success?: boolean;
            data?: components["schemas"]["PresignedUploadUrlResponse"];
            message?: string;
        };
        PresignedUploadUrlResponse: {
            presignedUrl?: string;
            fileKey?: string;
            accessUrl?: string;
        };
        ReissueRequest: {
            refreshToken: string;
        };
        ApiResponseLoginResponse: {
            success?: boolean;
            data?: components["schemas"]["LoginResponse"];
            message?: string;
        };
        LoginResponse: {
            accessToken?: string;
            refreshToken?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            data?: unknown;
            message?: string;
        };
        KakaoLoginRequest: {
            code: string;
        };
        UpdateUserRequest: {
            name: string;
        };
        ApiResponseUserResponse: {
            success?: boolean;
            data?: components["schemas"]["UserResponse"];
            message?: string;
        };
        UserResponse: {
            /** Format: int64 */
            id?: number;
            name?: string;
            profileImageUrl?: string;
            groupName?: string;
        };
        UpdateWorkLogRequest: {
            /**
             * @description 운영 로그 내용
             * @example 냉장고 점검 완료, 현재 온도 정상입니다.
             */
            content?: string;
            contentNotBlank?: boolean;
            updateFieldPresent?: boolean;
        };
        UpdateNoticeRequest: {
            /**
             * @description 공지 제목
             * @example 신상품 입고 안내 수정
             */
            title?: string;
            /**
             * @description 공지 내용
             * @example 신상품 진열 위치가 변경되었습니다.
             */
            content?: string;
            /**
             * @description 공지 태그
             * @example WEEKLY
             * @enum {string}
             */
            tag?: "DAILY" | "WEEKLY";
            /**
             * @description 첨부 이미지 URL
             * @example https://example.com/notices/updated-image.png
             */
            imageUrl?: string;
            /**
             * @description 기존 첨부 이미지 제거 여부
             * @example false
             */
            removeImage?: boolean;
            imageConflictFree?: boolean;
            updateFieldPresent?: boolean;
            fieldNotBlank?: boolean;
        };
        UpdateExpiryItemRequest: {
            /**
             * @description 상품명
             * @example 삼각김밥 전주비빔
             */
            productName?: string;
            /**
             * Format: date
             * @description 유통기한
             * @example 2026-07-11
             */
            expireDate?: string;
            /**
             * @description 상품 이미지 URL
             * @example https://example.com/expiry-items/updated.png
             */
            imageUrl?: string;
            updateFieldPresent?: boolean;
            fieldNotBlank?: boolean;
        };
        UpdateGroupRequest: {
            name?: string;
            /** @enum {string} */
            storeBrand?: "GS25" | "CU" | "SEVEN_ELEVEN" | "EMART24";
            nameValid?: boolean;
            atLeastOneFieldProvided?: boolean;
        };
        ApiResponseGroupResponse: {
            success?: boolean;
            data?: components["schemas"]["GroupResponse"];
            message?: string;
        };
        GroupResponse: {
            /** Format: int64 */
            groupId?: number;
            groupName?: string;
            /** @enum {string} */
            storeBrand?: "GS25" | "CU" | "SEVEN_ELEVEN" | "EMART24";
            inviteCode?: string;
            /** @enum {string} */
            role?: "OWNER" | "STAFF";
        };
        Pageable: {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            sort?: string[];
        };
        ApiResponsePageResponseWorkLogResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseWorkLogResponse"];
            message?: string;
        };
        PageResponseWorkLogResponse: {
            content?: components["schemas"]["WorkLogResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        ApiResponsePageResponseNoticeListResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseNoticeListResponse"];
            message?: string;
        };
        NoticeListResponse: {
            /**
             * Format: int64
             * @description 공지 ID
             * @example 1
             */
            noticeId?: number;
            /**
             * @description 공지 제목
             * @example 신상품 입고 안내
             */
            title?: string;
            /**
             * @description 공지 내용
             * @example 오늘 야간 근무자는 신상품 진열 상태를 확인해주세요.
             */
            content?: string;
            /**
             * @description 공지 태그
             * @example DAILY
             * @enum {string}
             */
            tag?: "DAILY" | "WEEKLY";
            /**
             * @description 첨부 이미지 URL
             * @example https://example.com/notices/image.png
             */
            imageUrl?: string;
            /**
             * Format: int64
             * @description 작성자 유저 ID
             * @example 1
             */
            authorUserId?: number;
            /**
             * @description 작성자 이름
             * @example 홍길동
             */
            authorName?: string;
            /**
             * Format: date-time
             * @description 작성 시각
             * @example 2026-07-02T10:30:00
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 표시 시작 시각
             * @example 2026-07-02T00:00:00
             */
            displayStartAt?: string;
            /**
             * Format: date-time
             * @description 표시 종료 시각, exclusive 기준
             * @example 2026-07-03T00:00:00
             */
            displayEndAt?: string;
        };
        PageResponseNoticeListResponse: {
            content?: components["schemas"]["NoticeListResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
        ApiResponseListGroupMemberResponse: {
            success?: boolean;
            data?: components["schemas"]["GroupMemberResponse"][];
            message?: string;
        };
        GroupMemberResponse: {
            /** Format: int64 */
            userId?: number;
            name?: string;
            profileImageUrl?: string;
            /** @enum {string} */
            role?: "OWNER" | "STAFF";
            /** Format: date-time */
            joinedAt?: string;
        };
        ApiResponsePageResponseExpiryItemResponse: {
            success?: boolean;
            data?: components["schemas"]["PageResponseExpiryItemResponse"];
            message?: string;
        };
        PageResponseExpiryItemResponse: {
            content?: components["schemas"]["ExpiryItemResponse"][];
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            size?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            totalPages?: number;
            hasNext?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    onboardStaff: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffOnboardingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseStaffOnboardingResponse"];
                };
            };
        };
    };
    onboardOwner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OwnerOnboardingRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseOwnerOnboardingResponse"];
                };
            };
        };
    };
    getWorkLogList: {
        parameters: {
            query: {
                from?: string;
                to?: string;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseWorkLogResponse"];
                };
            };
        };
    };
    createWorkLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateWorkLogRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkLogResponse"];
                };
            };
        };
    };
    getNoticeList: {
        parameters: {
            query: {
                tag?: "DAILY" | "WEEKLY";
                /** @description true이면 현재 유효한 공지만 조회합니다. */
                active?: boolean;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseNoticeListResponse"];
                };
            };
        };
    };
    createNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNoticeRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeResponse"];
                };
            };
        };
    };
    getExpiryItemList: {
        parameters: {
            query: {
                withinDays?: number;
                pageable: components["schemas"]["Pageable"];
            };
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePageResponseExpiryItemResponse"];
                };
            };
        };
    };
    createExpiryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateExpiryItemRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExpiryItemResponse"];
                };
            };
        };
    };
    createUploadUrl: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignedUploadUrlRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePresignedUploadUrlResponse"];
                };
            };
        };
    };
    reissue: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReissueRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    kakaoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KakaoLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseLoginResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateName: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseUserResponse"];
                };
            };
        };
    };
    getWorkLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                workLogId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkLogResponse"];
                };
            };
        };
    };
    deleteWorkLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                workLogId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateWorkLog: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                workLogId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkLogRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseWorkLogResponse"];
                };
            };
        };
    };
    getNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                noticeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeResponse"];
                };
            };
        };
    };
    deleteNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                noticeId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateNotice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                noticeId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNoticeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseNoticeResponse"];
                };
            };
        };
    };
    getExpiryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExpiryItemResponse"];
                };
            };
        };
    };
    deleteExpiryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateExpiryItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
                itemId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateExpiryItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseExpiryItemResponse"];
                };
            };
        };
    };
    getMyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    deleteMyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateMyGroup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGroupRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    reissueInviteCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseGroupResponse"];
                };
            };
        };
    };
    getList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListGroupMemberResponse"];
                };
            };
        };
    };
    leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                groupId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
}
